### ISSUE TITLE
Crear clase nueva llamada Columna

### ISSUE THREAD

**Issue by SaraVictorFernandez** [FundacioEsplaiJava2024/ToDoListGrupo4#9]

**Comment by SaraVictorFernandez** [comment]
Falta descripción 😢

**Comment by JordiJT99** [comment]
Crear una clase para añadir columnas que será hecho a través de un botón de añadir columna que nos permitirá elegir el nombre de esta. Más adelante se implementarán las funciones de editar columna y eliminar columna.
